### ISSUE TITLE
ExchangeOnlineManagement version limits

### ISSUE THREAD

**Issue by Bananovics** [grahamr975/EWS-Office365-Contact-Sync#73]
Hi,

Script is working fine with ExchangeOnlineManagement version 2.0.5 but it is not with 3.0.0. 
Similar issue described here: https://learn.microsoft.com/en-us/answers/questions/1023619/connect-exchangeonline-write-errormessage-expired.html

Can you please update commands in your script to solve limitations with version 3.0.0?

**Comment by christianneeb** [comment]
Adding to that this announcement from Microsoft: https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-deprecation-of-remote-powershell-rps-protocol-in/ba-p/3695597

**Comment by grahamr975** [comment]
Thanks for the heads up. I will push out an update for v3.0.0 compatibility before the depreciation.

**Comment by ggogel** [comment]
I can confirm this. As soon as you use any version higher than 2.0.5, the issue occurs. Though the issue only seems to occur with certificate-based authentication and only if you try to get more than 1000 objects. If I just run `Connect-ExchangeOnline` and run `(Get-Contact).Count`, the error does not appear and I get the full amount of contacts.

**Comment by grahamr975** [comment]
@Bananovics I'm aiming for early/mid-June.

**Comment by grahamr975** [comment]
I've opened a ticket with Microsoft and am awaiting feedback. The new version of ExchangeOnline broke the Get-User function. There are more details about the bug linked below...

https://github.com/MicrosoftDocs/office-docs-powershell/issues/10907

**Comment by pleongomez** [comment]
Hi, same issue with get-unifiedgroup function, is this broke too, like Get-User?

Thanks,
Regards.

**Comment by grahamr975** [comment]
@pleongomez
I think so. From what I've experienced, all of the non-ExO commands fail when returning 1000+ objects. Specifically, when using certificate authentication with 3.1.0 REST API.

**Comment by Bananovics** [comment]
I found a comment here: https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-deprecation-of-remote-powershell-rps-protocol-in/ba-p/3695597/page/2#comments

Says: "UPDATE: issue has been resolved. Just in case anybody else is getting the weird 'Expired or Invalid pagination request' error when using REST to fetch more than 1000 objects: apparently, you get this issue if you aren't using the .onmicrosoft.com domain for the -Organization parameter (although this does work in most cases). [Documentation for Connect-ExchangeOnline](https://learn.microsoft.com/en-us/powershell/module/exchange/connect-exchangeonline?view=exchange-ps#-organization) does state that 'you must use the primary .onmicrosoft.com domain of the organization', so be sure to check that."

I do not know if it helps but I thought it worth to share.

**Comment by grahamr975** [comment]
Just an update: Microsoft responded to our ticket by saying that the behavior is currently "by design" and to leave feedback here: https://feedbackportal.microsoft.com/feedback/post/. I'll have to find another workaround.

**Comment by grahamr975** [comment]
> I found a comment here: https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-deprecation-of-remote-powershell-rps-protocol-in/ba-p/3695597/page/2#comments
> 
> Says: "UPDATE: issue has been resolved. Just in case anybody else is getting the weird 'Expired or Invalid pagination request' error when using REST to fetch more than 1000 objects: apparently, you get this issue if you aren't using the .onmicrosoft.com domain for the -Organization parameter (although this does work in most cases). [Documentation for Connect-ExchangeOnline](https://learn.microsoft.com/en-us/powershell/module/exchange/connect-exchangeonline?view=exchange-ps#-organization) does state that 'you must use the primary .onmicrosoft.com domain of the organization', so be sure to check that."
> 
> I do not know if it helps but I thought it worth to share.

@Bananovics Thanks for researching this. Unfortunately, I still experience the same issue even when using our .onmicrosoft.com. Maybe someone else could have better luck?

**Comment by grahamr975** [comment]
I finally figured this out by throwing everything at the wall and seeing what stuck. For some reason, including the "ConnectionURI"  parameter with the Connect-ExchangeOnline cmdlet was the culprit. After removing this, everything is working fine. A new version is coming soon.
